site:
  title: Belief and Reason
  start_page: startpage::index.adoc 
content:
  sources: 
  - url: https://github.com/jcayouette/belief-and-reason
    branches: main
ui: 
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true