site:
  title: Belief and Reason
  start_page: intro-index::index.adoc 
  url: /

content:
  sources:

  - url: https://github.com/jcayouette/br-intro.git
    branches: main
    start_path: research

  - url: https://github.com/jcayouette/br-archeology.git
    branches: main

  - url: https://github.com/jcayouette/br-astronomy.git
    branches: main

  # - url: https://github.com/jcayouette/br-biology.git
  #   branches: main

  # - url: https://github.com/jcayouette/br-chemistry.git
  #   branches: main

  # - url: https://github.com/jcayouette/br-creation.git
  #   branches: main

  # - url: https://github.com/jcayouette/br-dailies.git
  #   branches: main

  # - url: https://github.com/jcayouette/br-evolution.git
  #   branches: main

  # - url: https://github.com/jcayouette/br-geology.git
  #   branches: main

  # - url: https://github.com/jcayouette/br-history.git
  #   branches: main

  # - url: https://github.com/jcayouette/br-information-science.git
  #   branches: main

  # - url: https://github.com/jcayouette/br-mathematics.git
  #   branches: main

  # - url: https://github.com/jcayouette/br-philosophy.git
  #   branches: main

  # - url: https://github.com/jcayouette/br-theology.git
  #   branches: main

ui: 
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true

asciidoc:
  attributes:

    br: 'Belief and Reason'

    #Asciidoc features
    linkattrs: true
    sectlinks: true
    sectnums: true
    sectnumlevels: 5
    toclevels: 3
    toc: left
    icons: font
    experimental: true
    idprefix: ''
    idseparator: '-'
    page-pagination: ''


output:
  dir: ./build
runtime:
  cache_dir: ./.cache/antora