site:
  title: Belief and Reason
  start_page: welcome::index.adoc 
  url: /



content:
  sources:

# br-root and introduction should be combined into one repo
  - url: https://github.com/jcayouette/br-intro.git
    branches: main

# Archeology
  - url: https://github.com/jcayouette/br-archeology.git
    branches: main

# Astronomy
#  - url: https://github.com/jcayouette/br-astronomy.git
#    branches: main

# Biology
  # - url: https://github.com/jcayouette/br-biology.git
  #   branches: main

# Chemistry
  # - url: https://github.com/jcayouette/br-chemistry.git
  #   branches: main

# Creation
  # - url: https://github.com/jcayouette/br-creation.git
  #   branches: main

# Devotional Studies
  # - url: https://github.com/jcayouette/br-dailies.git
  #   branches: main

# Evolution
  # - url: https://github.com/jcayouette/br-evolution.git
  #   branches: main

# Geology
  # - url: https://github.com/jcayouette/br-geology.git
  #   branches: main

# History
  # - url: https://github.com/jcayouette/br-history.git
  #   branches: main

# Information Science
  # - url: https://github.com/jcayouette/br-information-science.git
  #   branches: main

# Mathematics
  # - url: https://github.com/jcayouette/br-mathematics.git
  #   branches: main

# Philosophy
  # - url: https://github.com/jcayouette/br-philosophy.git
  #   branches: main

# Theology / Doctrine
  # - url: https://github.com/jcayouette/br-theology.git
  #   branches: main
ui: 
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true

asciidoc:
  attributes:

    br: 'Belief and Reason'

    #Asciidoc features
    linkattrs: true
    sectlinks: true
    sectnums: true
    sectnumlevels: 5
    toclevels: 3
    toc: left
    icons: font
    experimental: true

output:
  dir: ./build
runtime:
  cache_dir: ./.cache/antora